version: "3.9"
services:
  database:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  redis:
    image: redis:7
    command: []
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
  web:
    build: .
    command: gunicorn chatapp.asgi:application --workers 3 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=chatapp.settings
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin
    depends_on:
      - database
      - redis
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  database_data:
  redis_data:
